name: apiverve_inflation
description: Inflation Rate is a tool for retrieving annual inflation rate and CPI data for countries worldwide. It returns the inflation rate, CPI index value, and country details for any year going back to 1960.
version: 1.1.14
homepage: https://apiverve.com/marketplace/inflation?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/inflation-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
